# Generated by Django 6.0.3 on 2026-03-19 20:44

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role_type', models.CharField(choices=[('ADMIN', 'Admin'), ('MAINTAINER', 'Maintainer'), ('CONTRIBUTOR', 'Contributor')], default='CONTRIBUTOR', max_length=20)),
                ('bio', models.TextField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('positive_score', models.IntegerField(default=0)),
                ('negative_score', models.IntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False, help_text='User account credibility badge awarded by maintainers.')),
                ('github_username', models.CharField(blank=True, max_length=100)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'Users',
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('WIFI', 'Wi-Fi'), ('AUDIO', 'Audio'), ('GPU', 'GPU'), ('BLUETOOTH', 'Bluetooth'), ('INPUT', 'Input Device')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('driver', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Components',
                'ordering': ['type', 'name'],
                'unique_together': {('type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Distro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=50)),
                ('kernel_default', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Distros',
                'ordering': ['name', 'version'],
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='DriverFix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(help_text='Fix commands, terminal instructions, workarounds.')),
                ('external_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('mod_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_fixes', to='registry.component')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_fixes', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_fixes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Driver Fixes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('reason', models.CharField(choices=[('SPAM', 'Spam'), ('INCORRECT', 'Incorrect Information'), ('MISLEADING', 'Misleading'), ('DUPLICATE', 'Duplicate'), ('OTHER', 'Other')], max_length=15)),
                ('details', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('REVIEWED', 'Reviewed'), ('DISMISSED', 'Dismissed')], default='PENDING', max_length=10)),
                ('mod_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_flags', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Flags',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HelpGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('SUGGESTED', 'Suggested'), ('OPEN', 'Open'), ('RESOLVED', 'Resolved')], default='SUGGESTED', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_groups', to='registry.component')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_help_groups', to=settings.AUTH_USER_MODEL)),
                ('distro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_groups', to='registry.distro')),
                ('driver_fixes', models.ManyToManyField(blank=True, related_name='help_groups', to='registry.driverfix')),
            ],
            options={
                'verbose_name_plural': 'Help Groups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HelpGroupMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='registry.helpgroup')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='help_group_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Help Group Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=100)),
                ('series', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=200)),
                ('cpu_family', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Machines',
                'ordering': ['vendor', 'series', 'model_name'],
                'unique_together': {('vendor', 'series', 'model_name')},
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('MACHINE_DISTRO', 'Machine + Distro'), ('MACHINE_COMPONENT', 'Machine + Component'), ('COMPONENT_DISTRO', 'Component + Distro'), ('COMPONENT_ONLY', 'Component Only'), ('MACHINE_ONLY', 'Machine Only')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('boot_status', models.CharField(blank=True, choices=[('GOLD', 'Gold — Everything works out of the box'), ('SILVER', 'Silver — Most things work, minor issues'), ('BRONZE', 'Bronze — Usable with significant workarounds'), ('BROKEN', 'Broken — Does not boot or unusable')], help_text='Only applicable for MACHINE_DISTRO and MACHINE_ONLY report types.', max_length=10, null=True)),
                ('kernel_version', models.CharField(blank=True, help_text='e.g. 6.8.0-45 — override if user ran a non-default kernel.', max_length=50, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('compatibility_score', models.FloatField(blank=True, help_text='RESERVED: Do not populate manually. This field is reserved for future AI-powered compatibility assessment.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='registry.component')),
                ('distro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='registry.distro')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='registry.machine')),
                ('user', models.ForeignKey(help_text='SET_NULL so community reports survive account deletion.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_verified', models.BooleanField(default=False, help_text='Maintainer-verified accuracy badge.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='registry.report')),
            ],
            options={
                'verbose_name_plural': 'Comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Benchmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery_life_hours', models.FloatField(blank=True, null=True)),
                ('power_draw_watts', models.FloatField(blank=True, null=True)),
                ('cpu_score', models.IntegerField(blank=True, null=True)),
                ('gpu_score', models.IntegerField(blank=True, null=True)),
                ('suspend_resume_pass', models.BooleanField(blank=True, null=True)),
                ('suspend_resume_seconds', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benchmarks', to='registry.report')),
            ],
            options={
                'verbose_name_plural': 'Benchmarks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='report_attachments/%Y/%m/')),
                ('file_type', models.CharField(choices=[('IMAGE', 'Image'), ('LOG', 'Log File'), ('CONFIG', 'Config File')], max_length=10)),
                ('original_filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='registry.report')),
            ],
            options={
                'verbose_name_plural': 'Report Attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TrustEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('REPORT_UPVOTED', 'Report Upvoted'), ('REPORT_DOWNVOTED', 'Report Downvoted'), ('REPORT_APPROVED', 'Report Approved'), ('REPORT_REJECTED_PENALTY', 'Report Rejected (Penalty)'), ('COMMENT_VERIFIED', 'Comment Verified'), ('COMMENT_DOWNVOTED', 'Comment Downvoted'), ('COMMENT_FLAGGED_CONFIRMED', 'Comment Flag Confirmed'), ('DRIVER_FIX_ACCEPTED', 'Driver Fix Accepted'), ('DRIVER_FIX_REJECTED_PENALTY', 'Driver Fix Rejected (Penalty)')], max_length=40)),
                ('points_delta', models.IntegerField(help_text='Positive for gains, negative for penalties.')),
                ('mod_penalty_approved', models.BooleanField(default=False, help_text='Must be True for any PENALTY event before negative_score is updated. A signal listens for this transitioning to True and applies the deduction.')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_trust_events', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trust_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Trust Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HelpGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_status', models.CharField(choices=[('INVITED', 'Invited'), ('REQUESTED', 'Requested'), ('ACCEPTED', 'Accepted')], max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='registry.helpgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Help Group Memberships',
                'ordering': ['-joined_at'],
                'unique_together': {('group', 'user')},
            },
        ),
        migrations.CreateModel(
            name='CompStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('WORKING', 'Working'), ('ISSUES', 'Has Issues'), ('BROKEN', 'Broken')], max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_statuses', to='registry.component')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_statuses', to='registry.report')),
            ],
            options={
                'verbose_name_plural': 'Component Statuses',
                'ordering': ['component__type', 'component__name'],
                'unique_together': {('report', 'component')},
            },
        ),
        migrations.CreateModel(
            name='UserMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_machines', to='registry.machine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_machines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Machines',
                'ordering': ['-added_at'],
                'unique_together': {('user', 'machine')},
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('vote_type', models.CharField(choices=[('UPVOTE', 'Upvote'), ('DOWNVOTE', 'Downvote'), ('HELPFUL', 'Helpful'), ('NOT_HELPFUL', 'Not Helpful')], max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Votes',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'content_type', 'object_id')},
            },
        ),
    ]
