# Generated by Django 6.0.3 on 2026-03-22 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='form_factor',
            field=models.CharField(blank=True, choices=[('LAPTOP', 'Laptop'), ('DESKTOP', 'Desktop'), ('MINI_PC', 'Mini PC'), ('HANDHELD', 'Handheld'), ('ALL_IN_ONE', 'All-in-One')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='MachineSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_name', models.CharField(blank=True, help_text='e.g. Core i7-1365U', max_length=100, null=True)),
                ('cpu_manufacturer', models.CharField(blank=True, choices=[('INTEL', 'Intel'), ('AMD', 'AMD'), ('APPLE', 'Apple'), ('QUALCOMM', 'Qualcomm')], max_length=20, null=True)),
                ('cpu_generation', models.CharField(blank=True, help_text='e.g. 13th Gen, Zen 4', max_length=50, null=True)),
                ('cpu_series_tier', models.CharField(blank=True, choices=[('U', 'U Series (ultra-low power)'), ('P', 'P Series (performance)'), ('H', 'H Series (high performance)'), ('HX', 'HX Series (extreme)'), ('X', 'X Series (workstation)'), ('STANDARD', 'Standard (desktop / no tier)')], max_length=10, null=True)),
                ('gpu_name', models.CharField(blank=True, help_text='e.g. RTX 4060, Radeon 780M', max_length=100, null=True)),
                ('gpu_manufacturer', models.CharField(blank=True, choices=[('NVIDIA', 'NVIDIA'), ('AMD', 'AMD'), ('INTEL', 'Intel'), ('APPLE', 'Apple')], max_length=10, null=True)),
                ('gpu_generation', models.CharField(blank=True, help_text='e.g. Ada Lovelace, RDNA 3', max_length=50, null=True)),
                ('gpu_type', models.CharField(blank=True, choices=[('DEDICATED', 'Dedicated'), ('INTEGRATED', 'Integrated')], max_length=15, null=True)),
                ('ram_type', models.CharField(blank=True, choices=[('DDR4', 'DDR4'), ('DDR5', 'DDR5'), ('LPDDR4', 'LPDDR4'), ('LPDDR4X', 'LPDDR4X'), ('LPDDR5', 'LPDDR5'), ('LPDDR5X', 'LPDDR5X')], max_length=10, null=True)),
                ('ram_speed_mhz', models.IntegerField(blank=True, help_text='e.g. 4800, 5600', null=True)),
                ('ram_base_gb', models.IntegerField(blank=True, help_text='RAM as shipped in base config', null=True)),
                ('ram_max_gb', models.IntegerField(blank=True, help_text='Maximum supported RAM', null=True)),
                ('storage_type', models.CharField(blank=True, choices=[('NVME', 'NVMe SSD'), ('SATA', 'SATA SSD'), ('EMMC', 'eMMC')], max_length=10, null=True)),
                ('storage_base_gb', models.IntegerField(blank=True, help_text='Storage as shipped in base config', null=True)),
                ('storage_max_gb', models.IntegerField(blank=True, help_text='Max storage (null if soldered/non-upgradeable)', null=True)),
                ('display_size_inches', models.DecimalField(blank=True, decimal_places=1, help_text='e.g. 14.0, 15.6', max_digits=4, null=True)),
                ('display_resolution', models.CharField(blank=True, help_text='e.g. 1920x1200', max_length=20, null=True)),
                ('display_panel_type', models.CharField(blank=True, choices=[('IPS', 'IPS'), ('OLED', 'OLED'), ('AMOLED', 'AMOLED'), ('TN', 'TN'), ('VA', 'VA'), ('MINI_LED', 'Mini-LED')], max_length=10, null=True)),
                ('battery_wh', models.FloatField(blank=True, help_text='Battery capacity in Wh. Null for desktops.', null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('machine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spec', to='registry.machine')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_specs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Machine spec',
                'verbose_name_plural': 'Machine specs',
            },
        ),
        migrations.CreateModel(
            name='SpecSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text='The MachineSpec field this suggestion is for, e.g. cpu_name', max_length=50)),
                ('suggested_value', models.CharField(help_text='The suggested value as a string', max_length=200)),
                ('source_url', models.URLField(blank=True, help_text='Link to proof — manufacturer page, Notebookcheck, GSMArena etc.', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('mod_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_suggestions', to='registry.machine')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_suggestions', to=settings.AUTH_USER_MODEL)),
                ('suggested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spec_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Spec suggestion',
                'verbose_name_plural': 'Spec suggestions',
                'ordering': ['-created_at'],
            },
        ),
    ]
