# Generated by Django 6.0.3 on 2026-04-14 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_machine_form_factor_machinespec_specsuggestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpu_vram_gb', models.IntegerField(blank=True, help_text='VRAM in GB', null=True)),
                ('gpu_architecture', models.CharField(blank=True, choices=[('ADA_LOVELACE', 'Ada Lovelace (RTX 40xx)'), ('AMPERE', 'Ampere (RTX 30xx)'), ('TURING', 'Turing (RTX 20xx)'), ('RDNA4', 'RDNA 4 (RX 9xxx)'), ('RDNA3', 'RDNA 3 (RX 7xxx)'), ('RDNA2', 'RDNA 2 (RX 6xxx)'), ('INTEL_XE2', 'Intel Xe2 (Arc Battlemage)'), ('INTEL_XE', 'Intel Xe (Arc Alchemist)'), ('APPLE_GPU', 'Apple GPU'), ('INTEGRATED', 'Integrated (no dedicated)')], max_length=20, null=True)),
                ('gpu_tdp_watts', models.IntegerField(blank=True, help_text='TDP in watts', null=True)),
                ('gpu_memory_type', models.CharField(blank=True, choices=[('GDDR7', 'GDDR7'), ('GDDR6X', 'GDDR6X'), ('GDDR6', 'GDDR6'), ('LPDDR5', 'LPDDR5 (integrated)'), ('SHARED', 'Shared system RAM')], max_length=10, null=True)),
                ('gpu_generation', models.CharField(blank=True, help_text='e.g. RTX 40xx, RX 7xxx', max_length=50, null=True)),
                ('gpu_cuda_cores', models.IntegerField(blank=True, help_text='CUDA / Stream processors', null=True)),
                ('wifi_standard', models.CharField(blank=True, choices=[('WIFI7', 'WiFi 7 (802.11be)'), ('WIFI6E', 'WiFi 6E (802.11ax 6GHz)'), ('WIFI6', 'WiFi 6 (802.11ax)'), ('WIFI5', 'WiFi 5 (802.11ac)'), ('WIFI4', 'WiFi 4 (802.11n)')], max_length=10, null=True)),
                ('wifi_max_speed_mbps', models.IntegerField(blank=True, help_text='Max theoretical speed Mbps', null=True)),
                ('wifi_bands', models.CharField(blank=True, help_text='e.g. 2.4GHz, 5GHz, 6GHz', max_length=40, null=True)),
                ('wifi_bluetooth_ver', models.CharField(blank=True, help_text='Bluetooth version e.g. 5.3', max_length=10, null=True)),
                ('audio_codec', models.CharField(blank=True, help_text='e.g. Realtek ALC289', max_length=50, null=True)),
                ('audio_jack_detection', models.BooleanField(blank=True, null=True)),
                ('audio_hdmi_output', models.BooleanField(blank=True, null=True)),
                ('audio_microphone', models.BooleanField(blank=True, null=True)),
                ('audio_speakers', models.BooleanField(blank=True, null=True)),
                ('storage_interface', models.CharField(blank=True, choices=[('NVME_GEN5', 'NVMe PCIe Gen 5'), ('NVME_GEN4', 'NVMe PCIe Gen 4'), ('NVME_GEN3', 'NVMe PCIe Gen 3'), ('SATA', 'SATA SSD'), ('EMMC', 'eMMC'), ('UFS', 'UFS')], max_length=15, null=True)),
                ('storage_form_factor', models.CharField(blank=True, help_text='e.g. M.2 2280, M.2 2242', max_length=20, null=True)),
                ('storage_capacity_gb', models.IntegerField(blank=True, null=True)),
                ('storage_read_mbps', models.IntegerField(blank=True, help_text='Sequential read MB/s', null=True)),
                ('storage_write_mbps', models.IntegerField(blank=True, help_text='Sequential write MB/s', null=True)),
                ('display_size_inches', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('display_resolution', models.CharField(blank=True, help_text='e.g. 1920x1200', max_length=20, null=True)),
                ('display_refresh_hz', models.IntegerField(blank=True, null=True)),
                ('display_tech', models.CharField(blank=True, choices=[('IPS', 'IPS'), ('OLED', 'OLED'), ('AMOLED', 'AMOLED'), ('MINI_LED', 'Mini-LED'), ('TN', 'TN'), ('VA', 'VA')], max_length=10, null=True)),
                ('display_touch', models.BooleanField(blank=True, null=True)),
                ('display_hdr', models.BooleanField(blank=True, null=True)),
                ('display_brightness', models.IntegerField(blank=True, help_text='Max brightness in nits', null=True)),
                ('ethernet_speed_mbps', models.IntegerField(blank=True, help_text='e.g. 1000, 2500, 5000', null=True)),
                ('ethernet_chip', models.CharField(blank=True, help_text='e.g. Intel I219-V', max_length=50, null=True)),
                ('tb_version', models.CharField(blank=True, help_text='e.g. 4, 5, USB4', max_length=5, null=True)),
                ('tb_power_delivery', models.BooleanField(blank=True, null=True)),
                ('tb_display_output', models.BooleanField(blank=True, null=True)),
                ('tb_data_speed_gbps', models.IntegerField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Component spec',
                'verbose_name_plural': 'Component specs',
            },
        ),
        migrations.AddField(
            model_name='component',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='distro',
            name='based_on',
            field=models.CharField(blank=True, help_text='e.g. Debian, Arch', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='distro',
            name='desktop_default',
            field=models.CharField(blank=True, help_text='Default DE e.g. GNOME', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='distro',
            name='eol_date',
            field=models.DateField(blank=True, help_text='End of life date', null=True),
        ),
        migrations.AddField(
            model_name='distro',
            name='is_lts',
            field=models.BooleanField(default=False, help_text='Long-term support release'),
        ),
        migrations.AddField(
            model_name='distro',
            name='is_rolling',
            field=models.BooleanField(default=False, help_text='Rolling release e.g. Arch'),
        ),
        migrations.AddField(
            model_name='distro',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='distro',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='distro',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='type',
            field=models.CharField(choices=[('WIFI', 'WiFi'), ('AUDIO', 'Audio'), ('GPU', 'GPU'), ('BLUETOOTH', 'Bluetooth'), ('INPUT', 'Input device'), ('STORAGE', 'Storage (SSD/HDD/NVMe)'), ('DISPLAY', 'Display / Screen'), ('FINGERPRINT', 'Fingerprint reader'), ('WEBCAM', 'Webcam / Camera'), ('THUNDERBOLT', 'Thunderbolt / USB4'), ('ETHERNET', 'Ethernet / LAN'), ('CELLULAR', 'Cellular / WWAN / 5G'), ('USB_C', 'USB-C / Power delivery')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='component',
            index=models.Index(fields=['type'], name='registry_co_type_5dfa52_idx'),
        ),
        migrations.AddIndex(
            model_name='compstatus',
            index=models.Index(fields=['component', 'status'], name='registry_co_compone_2e9082_idx'),
        ),
        migrations.AddIndex(
            model_name='compstatus',
            index=models.Index(fields=['report', 'component'], name='registry_co_report__0e8115_idx'),
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['vendor'], name='registry_ma_vendor_4d40b7_idx'),
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['form_factor'], name='registry_ma_form_fa_26ea58_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status'], name='registry_re_status_1c26a4_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['boot_status'], name='registry_re_boot_st_673465_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['report_type'], name='registry_re_report__5db98e_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['created_at'], name='registry_re_created_817690_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', 'boot_status'], name='registry_re_status_89a3d8_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['user', 'status'], name='registry_re_user_id_55cb65_idx'),
        ),
        migrations.AddIndex(
            model_name='trustevent',
            index=models.Index(fields=['user', 'event_type'], name='registry_tr_user_id_4f7b66_idx'),
        ),
        migrations.AddIndex(
            model_name='trustevent',
            index=models.Index(fields=['mod_penalty_approved'], name='registry_tr_mod_pen_e4336e_idx'),
        ),
        migrations.AddField(
            model_name='componentspec',
            name='component',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spec', to='registry.component'),
        ),
        migrations.AddField(
            model_name='componentspec',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_component_specs', to=settings.AUTH_USER_MODEL),
        ),
    ]
